services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: docmost
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data:rw

  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data:rw

volumes:
  db_data:
  redis_data:
